*******************************************************************************
****** precharge schematic SRAM  <vs>  precharge layout SRAM
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    3       3
                                             ------  ------
Total                                             3       3

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45p1svt) MOS                                    3       3           3       3
                                             ------  ------      ------  ------
Total                                             3       3           3       3

Schematic and Layout Match
