*******************************************************************************
****** read_write schematic SRAM  <vs>  read_write layout SRAM
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                    4       4
(g45p1svt) MOS                                    2       2
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    4       4           4       4
(g45p1svt) MOS                                    2       2           2       2
                                             ------  ------      ------  ------
Total                                             6       6           6       6

Schematic and Layout Match
