*******************************************************************************
****** inverter schematic SRAM  <vs>  inverter layout SRAM
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    1       1
(g45n1svt) MOS                                    1       1
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    1       1           1       1
(g45p1svt) MOS                                    1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** senseamp schematic SRAM  <vs>  senseamp layout SRAM
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(inverter schematic SRAM, inverter) Cell          2       2
(g45n1svt) MOS                                    5       5
(g45p1svt) MOS                                    4       4
                                             ------  ------
Total                                            11      11

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(inverter) Cell                                   2       2           2       2
(g45n1svt) MOS                                    5       5           5       5
(g45p1svt) MOS                                    4       4           4       4
                                             ------  ------      ------  ------
Total                                            11      11          11      11

Schematic and Layout Match
